import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const samples = join(root, 'samples');
mkdirSync(samples, { recursive: true });

function writeBinaryPly(fileName, format, positions, faces, edges) {
  const le = format === 'binary_little_endian';
  const headerLines = [
    'ply',
    `format ${format} 1.0`,
    'comment generated by scripts/make_samples.mjs',
    `element vertex ${positions.length}`,
    'property float x',
    'property float y',
    'property float z',
  ];
  if (faces.length > 0) {
    headerLines.push(
      `element face ${faces.length}`,
      'property list uchar int vertex_indices',
    );
  }
  if (edges.length > 0) {
    headerLines.push(
      `element edge ${edges.length}`,
      'property int vertex1',
      'property int vertex2',
    );
  }
  headerLines.push('end_header');
  const headBytes = new TextEncoder().encode(headerLines.join('\n') + '\n');

  let bodySize = 0;
  bodySize += positions.length * 12;
  for (const f of faces) bodySize += 1 + f.length * 4;
  bodySize += edges.length * 8;

  const buf = new ArrayBuffer(headBytes.length + bodySize);
  new Uint8Array(buf).set(headBytes, 0);
  const dv = new DataView(buf, headBytes.length);
  let o = 0;
  for (const p of positions) {
    dv.setFloat32(o, p[0], le); o += 4;
    dv.setFloat32(o, p[1], le); o += 4;
    dv.setFloat32(o, p[2], le); o += 4;
  }
  for (const f of faces) {
    dv.setUint8(o, f.length); o += 1;
    for (const idx of f) {
      dv.setInt32(o, idx, le); o += 4;
    }
  }
  for (const e of edges) {
    dv.setInt32(o, e[0], le); o += 4;
    dv.setInt32(o, e[1], le); o += 4;
  }
  writeFileSync(join(samples, fileName), Buffer.from(buf));
  console.log(`wrote samples/${fileName} (${buf.byteLength} bytes)`);
}

const cubeVerts = [
  [-1, -1, -1], [1, -1, -1], [1, 1, -1], [-1, 1, -1],
  [-1, -1, 1], [1, -1, 1], [1, 1, 1], [-1, 1, 1],
];
const cubeQuads = [
  [0, 3, 2, 1],
  [4, 5, 6, 7],
  [0, 1, 5, 4],
  [1, 2, 6, 5],
  [2, 3, 7, 6],
  [3, 0, 4, 7],
];

writeBinaryPly('quad_binary_le.ply', 'binary_little_endian', cubeVerts, cubeQuads, []);
writeBinaryPly('quad_binary_be.ply', 'binary_big_endian', cubeVerts, cubeQuads, []);

const tetraVerts = [[0, 0, 0], [1, 0, 0], [0.5, 1, 0], [0.5, 0.5, 1]];
const tetraFaces = [[0, 2, 1], [0, 1, 3], [1, 2, 3], [0, 3, 2]];
const tetraEdges = [[0, 1], [0, 2], [0, 3], [1, 2], [1, 3], [2, 3]];
writeBinaryPly('tetra_binary_edges.ply', 'binary_little_endian', tetraVerts, tetraFaces, tetraEdges);
